feat: Migration feat
bitcointranscripts/transcription-review-backend pull request #110
Opened 2023-07-19 16:33 UTC by Toheeb-Ojuolape

2023-07-20 06:37 UTC, Extheoisah requested changes
This pr has commits from your lightning branch. If you want to include those commits here, pls apply my review comments on that pr here. 
If not, you need to clean up the commits to obly reflect the new migration and models

2023-07-20 21:41 UTC, Toheeb-Ojuolape commented
Hi @Extheoisah. As requested in your review, I uncommented the code I wrote in alby and opennode controllers and refactored them to work with the middleware setup. I also setup the node-lightning invoice package to decode invoices and get their amount to check if the user has sufficient sats in their wallet to request the withdrawal of that amount.

2023-07-21 07:54 UTC, nully0x commented
Hi @Toheeb-Ojuolape, the git-flow is a bit messed up, please update your local dev branch to the latest dev head and re-apply your work on that as a new branch. That should make it easier.

2023-07-21 07:56 UTC, Toheeb-Ojuolape commented
> Hi @Toheeb-Ojuolape, the git-flow is a bit messed up, please update your local dev branch to the latest dev head and re-apply your work on that as a new branch. That should make it easier.

I already did a rebase to dev. Is there something else I'm supposed to do again?

2023-07-21 09:13 UTC, nully0x commented
> > Hi @Toheeb-Ojuolape, the git-flow is a bit messed up, please update your local dev branch to the latest dev head and re-apply your work on that as a new branch. That should make it easier.
> 
> @nully0x I already did a rebase to dev. Is there something else I'm supposed to do again?

oh okay, don't worry.

2023-07-21 10:19 UTC, nully0x commented on api/app/controllers/opennode.controller.ts
> +  if (timestamp + 5 * 60 * 1000 < Date.now()) {
I think we should have the timestamp and the calculation as a constant

2023-07-21 10:26 UTC, nully0x commented on api/app/controllers/opennode.controller.ts
> +  if (typeof amount != "number") {
Here, we should handle this more explicitly, you can add an additional check to verify that the amount is a valid number and not NaN.  
say 

```
if (typeof amount !== "number" || isNaN(amount)) {
  res.status(400).send({ message: "You need to enter a valid amount" });
  return;
}
```

2023-07-21 10:50 UTC, nully0x commented on api/app/helpers/albyToken.ts
For clarity, we should use a fetch or axios for API calls, better if we could use async/await format.

- for each function, I suggest something like this:

```
export async function fetchUserToken(code: string) {
  try {
    const response = await axios.post(
      process.env.ALBY_TOKEN_API,
      new URLSearchParams({
        code: code,
        grant_type: "authorization_code",
        redirect_uri: process.env.REDIRECT_URL,
      }),
      {
        headers: {
          Authorization:
            "Basic " +
            Buffer.from(
              process.env.ALBY_CLIENT_ID + ":" + process.env.ALBY_SECRET_ID
            ).toString("base64"),
        },
      }
    );
    return response.data;
  } catch (error: any) {
    throw new Error(error.message);
  }
}
```
```
export async function fetchAccessToken(req: Request) {
  try {
    const response = await axios.post(
      process.env.ALBY_TOKEN_API,
      new URLSearchParams({
        refresh_token: req.body.refreshToken,
        grant_type: "refresh_token",
      }),
      {
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization:
            "Basic " +
            Buffer.from(
              process.env.ALBY_CLIENT_ID + ":" + process.env.ALBY_SECRET_ID
            ).toString("base64"),
        },
      }
    );
    return response.data;
  } catch (error: any) {
    throw new Error(error.message);
  }
}
```

where instead of request we could use Axios or since we bumped to node 18 in prod we could use the native fetch.

- Also, using new URLSearchParams() to handle the request body in the x-www-form-urlencoded format required for token requests. This way, we can avoid using the formData field specific to the request library.

2023-07-21 10:52 UTC, nully0x commented on api/app/controllers/alby.controller.ts
> +    const info: any = await fetchInvoice(tokens, req);
what are we expecting info to be aside `any`

2023-07-21 10:55 UTC, nully0x commented on api/app/controllers/alby.controller.ts
> +    const userTokens: any = await fetchUserToken(code);
Let's try and catch all types properly aside `any`

2023-07-26 23:06 UTC, closed without merging