Db modify
bitcointranscripts/transcription-review-backend pull request #90
Opened 2023-07-03 22:25 UTC by nully0x

This PR made changes to db tables as referenced in issue #54

2023-07-03 23:51 UTC, Extheoisah requested changes

2023-07-03 23:51 UTC, Extheoisah commented on api/app/sequelize/migrations/20230703214456-modify_pr_url.js
> +      'email_address',
You need to add this field to the users model

2023-07-03 23:51 UTC, Extheoisah commented on api/app/sequelize/migrations/20230703214456-modify_pr_url.js
> +      'jwt',
Same here -> add to the user model

2023-07-04 00:48 UTC, nully0x commented on api/app/sequelize/migrations/20230703214456-modify_pr_url.js
> +      'jwt',
Did you run it locally??

2023-07-06 19:07 UTC, Extheoisah commented
closing this PR. the issue has been resolved by https://github.com/bitcointranscripts/transcription-review-backend/pull/56

2023-07-06 19:07 UTC, closed without merging